[package]
name = "container-device-interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "cdi" # Name of the binary executable
path = "src/bin/cdi.rs" # Path to the source file



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oci-spec = "0.6.4"
anyhow = "1.0"