[package]
name = "cdi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cdi" # Name of the binary executable
path = "src/bin/cdi.rs" # Path to the source file

[[bin]]
name = "validate" # Name of the binary executable
path = "src/bin/validate.rs" # Path to the source file



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oci-spec = "0.6.4"
anyhow = "1.0"
clap = "4.5.3"
serde_json = "1.0"
jsonschema = "0.17.1"
once_cell = "1.8.0"
notify = "4.0.15" 
serde = "1.0.131"
serde_derive = "1.0.131"
libc = "0.2.112"
nix = "0.28.0"

[dev-dependencies]
tempfile = "3.1.0"
